import type { Product } from "../lib/types";
import { APPAREL_SIZES, SHOE_SIZES } from "../lib/types";

const apparelSizes = [...APPAREL_SIZES];
const shoeSizes = [...SHOE_SIZES];

export const products: Product[] = [
  {
    id: "dri-fit-tee",
    name: "เสื้อกีฬา Dri-Fit",
    description: "เสื้อคลี่คลาย ระบายอากาศดี เหมาะวิ่งและออกกำลังกายกลางแจ้ง",
    longDescription:
      "เสื้อกีฬา Dri-Fit ผ้าระบายความชื้น น้ำหนักเบา แห้งเร็ว เหมาะสำหรับวิ่ง ออกกำลังกายกลางแจ้ง หรือคลาสกรุ๊ปฟิตเนส ดีไซน์คลี่คลายไม่รัดแน่น สวมใส่สบายตลอดการเคลื่อนไหว",
    category: "top",
    image: "/products/dri-fit-tee.jpg",
    pricePerRental: 49,
    material: "โพลีเอสเตอร์ รีไซเคิล 100%",
    color: "เขียวมิ้นท์",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "ระบายอากาศดี แห้งเร็ว",
      "ผ้ารีไซเคิล เป็นมิตรกับสิ่งแวดล้อม",
      "ตะเข็บแบน ลดการเสียดสี",
      "ซักฆ่า Ozone ทุกครั้งหลังคืน",
    ],
    activities: ["วิ่ง", "คาร์ดิโอ", "เวทเทรนนิ่ง", "ปั่นจักรยาน"],
    sizeGuide: [
      { size: "XS", chest: "76–81 ซม." },
      { size: "S", chest: "81–86 ซม." },
      { size: "M", chest: "86–91 ซม." },
      { size: "L", chest: "91–97 ซม." },
      { size: "XL", chest: "97–102 ซม." },
    ],
    careNote:
      "ทุกชิ้นผ่านกระบวนการซัก ฆ่าเชื้อด้วย Ozone และบรรจุในซิปล็อกย่อยสลายได้ก่อนส่งมอบ",
  },
  {
    id: "running-shorts",
    name: "กางเกงวิ่ง สั้น",
    description: "กางเกงสั้นเบา สะดวกสบาย มีกระเป๋าซ่อนด้านหลัง",
    longDescription:
      "กางเกงวิ่งสั้นสายรัดเอวยืดหยุ่น ผ้าเบาไม่ติดตัว มีกระเป๋าซ่อนด้านหลังสำหรับกุญแจหรือการ์ด เหมาะวิ่งในอากาศร้อน หรือออกกำลังกายที่ต้องการความคล่องตัวสูง",
    category: "bottom",
    image: "/products/running-shorts-navy.jpg",
    pricePerRental: 39,
    material: "โพลีเอสเตอร์ 88% + สแปนเด็กซ์ 12%",
    color: "น้ำเงิน",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "น้ำหนักเบา ระบายอากาศ",
      "สายรัดเอวยืดหยุ่น",
      "กระเป๋าซ่อนด้านหลัง",
      "แห้งเร็วหลังซัก",
    ],
    activities: ["วิ่ง", "สปรินต์", "HIIT", "เดินเร็ว"],
    sizeGuide: [
      { size: "XS", waist: "58–61 ซม." },
      { size: "S", waist: "61–66 ซม." },
      { size: "M", waist: "66–71 ซม." },
      { size: "L", waist: "71–76 ซม." },
      { size: "XL", waist: "76–81 ซม." },
    ],
    careNote:
      "ตรวจสอบกระเป๋าและซิปทุกครั้งก่อนส่งมอบ ซักแยกตามมาตรฐานสุขอนามัยของ Tua Plew",
  },
  {
    id: "leggings",
    name: "กางเกงยาว วิ่ง",
    description: "กางเกงยาวรัดรูป ยืดหยุ่นสูง เหมาะโยคะและวิ่ง",
    longDescription:
      "กางเกงยาวรัดรูประดับกลาง เอวสูงช่วยพยุง ผ้ายืดสี่ทิศทางไม่บีบรัดจนเกินไป เหมาะโยคะ พิลาทิส วิ่ง หรือออกกำลังกายในร่ม",
    category: "bottom",
    image: "/products/leggings.jpg",
    pricePerRental: 59,
    material: "ไนลอน 75% + สแปนเด็กซ์ 25%",
    color: "ม่วง",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "ยืดสี่ทิศทาง คล่องตัว",
      "เอวสูงพยุงสบาย",
      "ไร้ตะเข็บด้านข้าง ลดการเสียดสี",
      "ไม่โปร่งแสง",
    ],
    activities: ["โยคะ", "พิลาทิส", "วิ่ง", "เต้นแอโรบิก"],
    sizeGuide: [
      { size: "XS", waist: "56–59 ซม." },
      { size: "S", waist: "59–64 ซม." },
      { size: "M", waist: "64–69 ซม." },
      { size: "L", waist: "69–74 ซม." },
      { size: "XL", waist: "74–79 ซม." },
    ],
    careNote:
      "ตรวจสอบความยืดหยุ่นของผ้าหลังซักทุกครั้ง เพื่อความพอดีและความสบายในการสวมใส่",
  },
  {
    id: "yoga-set",
    name: "ชุดโยคะ ครบเซ็ต",
    description: "เสื้อ + กางเกงยาว ชุดเดียวจบ พร้อมออกกำลังกายทันที",
    longDescription:
      "ชุดโยคะครบเซ็ตประกอบด้วยเสื้อคลี่คลายและกางเกงยาวรัดรูป ผ้าคอตตอนออร์แกนิกนุ่มสบาย เหมาะสำหรับโยคะ พิลาทิส สตรีทชิง หรือออกกำลังกายเบาๆ ชุดเดียวจบ ไม่ต้องเลือกแยก",
    category: "set",
    image: "/products/yoga-set.jpg",
    pricePerRental: 89,
    material: "ผ้าคอตตอนออร์แกนิก 95% + สแปนเด็กซ์ 5%",
    color: "ส้มคอรัล",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "ครบเซ็ต เสื้อ + กางเกง",
      "ผ้าออร์แกนิก สัมผัสนุ่ม",
      "ดีไซน์เรียบ เหมาะทุกคลาส",
      "ประหยัดกว่าเช่าแยกชิ้น",
    ],
    activities: ["โยคะ", "พิลาทิส", "สตรีทชิง", "เต้นแอโรบิก"],
    sizeGuide: [
      { size: "XS", chest: "76–81 ซม.", waist: "56–59 ซม." },
      { size: "S", chest: "81–86 ซม.", waist: "59–64 ซม." },
      { size: "M", chest: "86–91 ซม.", waist: "64–69 ซม." },
      { size: "L", chest: "91–97 ซม.", waist: "69–74 ซม." },
      { size: "XL", chest: "97–102 ซม.", waist: "74–79 ซม." },
    ],
    careNote:
      "ชุดเซ็ตบรรจุแยกชิ้นในถุงซิปล็อกคู่ เพื่อความสะอาดและง่ายต่อการตรวจสอบก่อนส่งมอบ",
  },
  {
    id: "running-shoes",
    name: "รองเท้าวิ่ง",
    description: "รองเท้าวิ่งเบา รองรับแรงกระแทก ระบายอากาศดี",
    longDescription:
      "รองเท้าวิ่งออกแบบสำหรับวิ่งบนทางเรียบและในอาคาร โฟมรองรับแรงกระแทกกลาง พื้นยางกันลื่น ตาข่ายระบายอากาศ สวมใส่ง่ายด้วยระบบลิ้นไม่ต้องผูกเชือก เหมาะวิ่ง 5–10 กม. หรือคลาสคาร์ดิโอ",
    category: "shoe",
    image: "/products/running-shoes.jpg",
    pricePerRental: 69,
    material: "ตาข่ายผ้า + โฟม EVA + พื้นยาง",
    color: "เทา-ส้ม",
    sizes: shoeSizes,
    sizeUnit: "คู่",
    features: [
      "น้ำหนักเบา รองรับแรงกระแทก",
      "พื้นยางกันลื่น",
      "ระบายอากาศดี",
      "ทำความสะอาดและฆ่าเชื้อทุกครั้ง",
    ],
    activities: ["วิ่ง", "เดินเร็ว", "คาร์ดิโอ", "เทรดมิล"],
    sizeGuide: [
      { size: "38", footLength: "24.0 ซม." },
      { size: "39", footLength: "24.5 ซม." },
      { size: "40", footLength: "25.0 ซม." },
      { size: "41", footLength: "25.5 ซม." },
      { size: "42", footLength: "26.0 ซม." },
      { size: "43", footLength: "26.5 ซม." },
    ],
    careNote:
      "รองเท้าทุกคู่ผ่านการทำความสะอาด ฆ่าเชื้อด้วย UV และ Ozone บรรจุถุงซิปล็อกแยกคู่ก่อนส่งมอบ",
  },
  {
    id: "training-shoes",
    name: "รองเท้าออกกำลังกาย",
    description: "รองเท้าสำหรับเวทและฟังก์ชันนัล เกาะพื้นดี มั่นคง",
    longDescription:
      "รองเท้าออกกำลังกายหน้ากว้าง พื้นแบนราบช่วยเกาะพื้น โฟมรองรับส้นเท้า เหมาะเวทเทรนนิ่ง ฟังก์ชันนัล เต้นแอโรบิก หรือคลาสกรุ๊ปในร่ม สวมใส่สบาย ไม่บีบเท้า",
    category: "shoe",
    image: "/products/training-shoes.jpg",
    pricePerRental: 65,
    material: "หนังสังเคราะห์ + โฟม + พื้นยาง",
    color: "ดำ-เขียว",
    sizes: shoeSizes,
    sizeUnit: "คู่",
    features: [
      "หน้ากว้าง สวมใส่สบาย",
      "พื้นแบนราบ เกาะพื้นดี",
      "เหมาะเวทและฟังก์ชันนัล",
      "ทำความสะอาดและฆ่าเชื้อทุกครั้ง",
    ],
    activities: ["เวทเทรนนิ่ง", "ฟังก์ชันนัล", "HIIT", "เต้นแอโรบิก"],
    sizeGuide: [
      { size: "38", footLength: "24.0 ซม." },
      { size: "39", footLength: "24.5 ซม." },
      { size: "40", footLength: "25.0 ซม." },
      { size: "41", footLength: "25.5 ซม." },
      { size: "42", footLength: "26.0 ซม." },
      { size: "43", footLength: "26.5 ซม." },
    ],
    careNote:
      "ตรวจสอบพื้นรองเท้าและตะเข็บทุกครั้งหลังคืน ทำความสะอาดและฆ่าเชื้อก่อนส่งมอบลูกค้าคนถัดไป",
  },
  {
    id: "nike-pegasus",
    name: "Nike Air Zoom Pegasus",
    description: "รองเท้าวิ่งจาก Nike โฟมรองรับแรงกระแทก React สบายเท้า",
    longDescription:
      "รองเท้าวิ่ง Nike Air Zoom Pegasus จากแบรนด์พาร์ทเนอร์ เหมาะวิ่งระยะกลาง โฟม React รองรับแรงกระแทก ตาข่ายระบายอากาศ น้ำหนักเบา ทุกคู่ผ่านการทำความสะอาดมาตรฐาน Tua Plew ก่อนส่งมอบ",
    category: "shoe",
    image: "/products/running-shoes.jpg",
    pricePerRental: 89,
    material: "ตาข่าย Flymesh + โฟม React + พื้นยาง",
    color: "ขาว-ดำ",
    sizes: shoeSizes,
    sizeUnit: "คู่",
    brand: "Nike",
    isPartnerBrand: true,
    features: [
      "โฟม React รองรับแรงกระแทก",
      "น้ำหนักเบา เหมาะวิ่งระยะกลาง",
      "ตาข่ายระบายอากาศดี",
      "แบรนด์พาร์ทเนอร์ คุณภาพมาตรฐาน",
    ],
    activities: ["วิ่ง", "เดินเร็ว", "คาร์ดิโอ", "เทรดมิล"],
    sizeGuide: [
      { size: "38", footLength: "24.0 ซม." },
      { size: "39", footLength: "24.5 ซม." },
      { size: "40", footLength: "25.0 ซม." },
      { size: "41", footLength: "25.5 ซม." },
      { size: "42", footLength: "26.0 ซม." },
      { size: "43", footLength: "26.5 ซม." },
    ],
    careNote:
      "รองเท้าแบรนด์พาร์ทเนอร์ทุกคู่ผ่านการทำความสะอาด ฆ่าเชื้อ UV และ Ozone บรรจุถุงซิปล็อกแยกคู่",
  },
  {
    id: "adidas-ultraboost",
    name: "Adidas Ultraboost",
    description: "รองเท้าวิ่ง Adidas โฟม Boost ตอบสนองดี สวมใส่สบาย",
    longDescription:
      "รองเท้า Adidas Ultraboost จากแบรนด์พาร์ทเนอร์ โฟม Boost ตอบสนองดี Primeknit หุ้มเท้าพอดี เหมาะวิ่งและเดินระยะไกล ทุกคู่ผ่านการทำความสะอาดมาตรฐาน Tua Plew",
    category: "shoe",
    image: "/products/training-shoes.jpg",
    pricePerRental: 95,
    material: "Primeknit + โฟม Boost + พื้นยาง Continental",
    color: "ดำ-ขาว",
    sizes: shoeSizes,
    sizeUnit: "คู่",
    brand: "Adidas",
    isPartnerBrand: true,
    features: [
      "โฟม Boost ตอบสนองดี",
      "Primeknit หุ้มเท้าพอดี",
      "พื้นยาง Continental กันลื่น",
      "แบรนด์พาร์ทเนอร์ คุณภาพมาตรฐาน",
    ],
    activities: ["วิ่ง", "เดินเร็ว", "คาร์ดิโอ", "เทรดมิล"],
    sizeGuide: [
      { size: "38", footLength: "24.0 ซม." },
      { size: "39", footLength: "24.5 ซม." },
      { size: "40", footLength: "25.0 ซม." },
      { size: "41", footLength: "25.5 ซม." },
      { size: "42", footLength: "26.0 ซม." },
      { size: "43", footLength: "26.5 ซม." },
    ],
    careNote:
      "รองเท้าแบรนด์พาร์ทเนอร์ทุกคู่ผ่านการทำความสะอาด ฆ่าเชื้อ UV และ Ozone บรรจุถุงซิปล็อกแยกคู่",
  },
  {
    id: "nb-1080",
    name: "New Balance Fresh Foam 1080",
    description: "รองเท้าวิ่ง New Balance โฟม Fresh Foam X นุ่มสบาย",
    longDescription:
      "รองเท้า New Balance Fresh Foam 1080 จากแบรนด์พาร์ทเนอร์ โฟม Fresh Foam X นุ่มสบาย เหมาะวิ่งระยะยาวและ recovery run ทุกคู่ผ่านการทำความสะอาดมาตรฐาน Tua Plew",
    category: "shoe",
    image: "/products/running-shoes.jpg",
    pricePerRental: 85,
    material: "ตาข่าย Engineered Mesh + โฟม Fresh Foam X",
    color: "เทา-ฟ้า",
    sizes: shoeSizes,
    sizeUnit: "คู่",
    brand: "New Balance",
    isPartnerBrand: true,
    features: [
      "โฟม Fresh Foam X นุ่มสบาย",
      "เหมาะวิ่งระยะยาว",
      "ตาข่ายระบายอากาศ",
      "แบรนด์พาร์ทเนอร์ คุณภาพมาตรฐาน",
    ],
    activities: ["วิ่ง", "เดินเร็ว", "คาร์ดิโอ", "เทรดมิล"],
    sizeGuide: [
      { size: "38", footLength: "24.0 ซม." },
      { size: "39", footLength: "24.5 ซม." },
      { size: "40", footLength: "25.0 ซม." },
      { size: "41", footLength: "25.5 ซม." },
      { size: "42", footLength: "26.0 ซม." },
      { size: "43", footLength: "26.5 ซม." },
    ],
    careNote:
      "รองเท้าแบรนด์พาร์ทเนอร์ทุกคู่ผ่านการทำความสะอาด ฆ่าเชื้อ UV และ Ozone บรรจุถุงซิปล็อกแยกคู่",
  },
  {
    id: "on-cloudrunner",
    name: "On Cloudrunner",
    description: "รองเท้าวิ่ง On น้ำหนักเบา ระบบ CloudTec รองรับแรงกระแทก",
    longDescription:
      "รองเท้า On Cloudrunner จากแบรนด์พาร์ทเนอร์ ระบบ CloudTec รองรับแรงกระแทก น้ำหนักเบา เหมาะวิ่งและเดินในเมือง ทุกคู่ผ่านการทำความสะอาดมาตรฐาน Tua Plew",
    category: "shoe",
    image: "/products/training-shoes.jpg",
    pricePerRental: 99,
    material: "ตาข่าย Engineered Mesh + CloudTec + Helion โฟม",
    color: "ขาว-ฟ้า",
    sizes: shoeSizes,
    sizeUnit: "คู่",
    brand: "On",
    isPartnerBrand: true,
    features: [
      "ระบบ CloudTec รองรับแรงกระแทก",
      "น้ำหนักเบามาก",
      "เหมาะวิ่งและเดินในเมือง",
      "แบรนด์พาร์ทเนอร์ คุณภาพมาตรฐาน",
    ],
    activities: ["วิ่ง", "เดินเร็ว", "คาร์ดิโอ", "เทรดมิล"],
    sizeGuide: [
      { size: "38", footLength: "24.0 ซม." },
      { size: "39", footLength: "24.5 ซม." },
      { size: "40", footLength: "25.0 ซม." },
      { size: "41", footLength: "25.5 ซม." },
      { size: "42", footLength: "26.0 ซม." },
      { size: "43", footLength: "26.5 ซม." },
    ],
    careNote:
      "รองเท้าแบรนด์พาร์ทเนอร์ทุกคู่ผ่านการทำความสะอาด ฆ่าเชื้อ UV และ Ozone บรรจุถุงซิปล็อกแยกคู่",
  },
  {
    id: "sports-tank-top",
    name: "เสื้อกล้ามกีฬา",
    description: "เสื้อกล้ามเบา ระบายอากาศดี เหมาะคาร์ดิโอและกีฬาหลากหลาย",
    longDescription:
      "เสื้อกล้ามกีฬาผ้าโพลีเอสเตอร์บางเบา ระบายความชื้น แขนกว้างคล่องตัว เหมาะวิ่ง แบดมินตัน แอโรบิก หรือออกกำลังกายกลางแจ้งในอากาศร้อน",
    category: "top",
    image: "/products/sports-tank-top.jpg",
    pricePerRental: 35,
    material: "โพลีเอสเตอร์ 92% + สแปนเด็กซ์ 8%",
    color: "ฟ้า",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "น้ำหนักเบามาก",
      "ระบายอากาศดี",
      "แขนกว้าง คล่องตัว",
      "แห้งเร็วหลังซัก",
    ],
    activities: ["วิ่ง", "แบดมินตัน", "แอโรบิก", "ปั่นจักรยาน"],
    sizeGuide: [
      { size: "XS", chest: "74–79 ซม." },
      { size: "S", chest: "79–84 ซม." },
      { size: "M", chest: "84–89 ซม." },
      { size: "L", chest: "89–95 ซม." },
      { size: "XL", chest: "95–100 ซม." },
    ],
    careNote:
      "ทุกชิ้นผ่านกระบวนการซัก ฆ่าเชื้อด้วย Ozone และบรรจุในซิปล็อกย่อยสลายได้ก่อนส่งมอบ",
  },
  {
    id: "training-pants",
    name: "กางเกงขายาววอร์มอัพ",
    description: "กางเกงขายาวเบา ใส่สบาย เหมาะวอร์มอัพก่อนออกกำลังกาย",
    longDescription:
      "กางเกงขายาววอร์มอัพผ้าเบา ยืดหยุ่น เอวยางยืด ใส่สบายก่อน–หลังออกกำลังกาย หรือใช้เดินเบาๆ ในวันพักฟื้น",
    category: "bottom",
    image: "/products/training-pants.jpg",
    pricePerRental: 45,
    material: "โพลีเอสเตอร์ 85% + สแปนเด็กซ์ 15%",
    color: "เทา",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "ผ้าเบา ใส่สบาย",
      "เอวยางยืด",
      "เหมาะวอร์มอัพ",
      "ซักแห้งเร็ว",
    ],
    activities: ["วอร์มอัพ", "เดิน", "ยืดเหยียด", "ฟื้นฟู"],
    sizeGuide: [
      { size: "XS", waist: "58–61 ซม." },
      { size: "S", waist: "61–66 ซม." },
      { size: "M", waist: "66–71 ซม." },
      { size: "L", waist: "71–76 ซม." },
      { size: "XL", waist: "76–81 ซม." },
    ],
    careNote:
      "ตรวจสอบยางรัดเอวทุกครั้งก่อนส่งมอบ ซักตามมาตรฐานสุขอนามัยของ Tua Plew",
  },
  {
    id: "walk-shoes",
    name: "รองเท้าเดินกีฬา",
    description: "รองเท้าเบา สวมใส่สบาย เหมาะเดินและคาร์ดิโอเบาๆ",
    longDescription:
      "รองเท้าเดินกีฬาน้ำหนักเบา โฟมรองรับส้นเท้า พื้นยางกันลื่น เหมาะเดินเร็ว คาร์ดิโอเบาๆ หรือใช้งานทั่วไปในฟิตเนส",
    category: "shoe",
    image: "/products/walk-shoes.jpg",
    pricePerRental: 59,
    material: "ตาข่ายผ้า + โฟม EVA + พื้นยาง",
    color: "เทา-ขาว",
    sizes: shoeSizes,
    sizeUnit: "คู่",
    features: [
      "น้ำหนักเบา",
      "สวมใส่สบาย",
      "พื้นยางกันลื่น",
      "ทำความสะอาดทุกครั้ง",
    ],
    activities: ["เดินเร็ว", "คาร์ดิโอ", "เทรดมิล", "ฟื้นฟู"],
    sizeGuide: [
      { size: "38", footLength: "24.0 ซม." },
      { size: "39", footLength: "24.5 ซม." },
      { size: "40", footLength: "25.0 ซม." },
      { size: "41", footLength: "25.5 ซม." },
      { size: "42", footLength: "26.0 ซม." },
      { size: "43", footLength: "26.5 ซม." },
    ],
    careNote:
      "รองเท้าทุกคู่ผ่านการทำความสะอาด ฆ่าเชื้อด้วย UV และ Ozone บรรจุถุงซิปล็อกแยกคู่",
  },
  {
    id: "yoga-bra",
    name: "เสื้อสปอร์ตบรา",
    description: "บรารองรับดี ใส่สบาย เหมาะโยคะและพิลาทิส",
    longDescription:
      "เสื้อสปอร์ตบราผ้ายืดหยุ่น รองรับระดับกลาง ไม่บีบรัดจนเกินไป สายรัดไม่หลุดง่าย เหมาะโยคะ พิลาทิส บาร์ และคลาสในร่ม",
    category: "top",
    image: "/products/yoga-bra.jpg",
    pricePerRental: 45,
    material: "ไนลอน 80% + สแปนเด็กซ์ 20%",
    color: "ม่วง",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "รองรับระดับกลาง",
      "ผ้ายืดหยุ่นสูง",
      "สายรัดมั่นคง",
      "ไม่ระคายผิว",
    ],
    activities: ["โยคะ", "พิลาทิส", "บาร์", "สตรีทชิง"],
    sizeGuide: [
      { size: "XS", chest: "74–79 ซม." },
      { size: "S", chest: "79–84 ซม." },
      { size: "M", chest: "84–89 ซม." },
      { size: "L", chest: "89–95 ซม." },
      { size: "XL", chest: "95–100 ซม." },
    ],
    careNote:
      "ซักแยกตามมาตรฐานสุขอนามัย ตรวจสอบความยืดหยุ่นของผ้าหลังซักทุกครั้ง",
  },
  {
    id: "pilates-shorts",
    name: "กางเกงขาสั้นโยคะ",
    description: "กางเกงสั้นรัดรูป ยืดสี่ทิศทาง ไม่โปร่งแสง",
    longDescription:
      "กางเกงขาสั้นโยคะเอวสูง ผ้ายืดสี่ทิศทางกระชับพอดี ไม่โปร่งแสงเมื่อก้มหรือยืด เหมาะโยคะ พิลาทิส และบาร์",
    category: "bottom",
    image: "/products/pilates-shorts.jpg",
    pricePerRental: 49,
    material: "ไนลอน 78% + สแปนเด็กซ์ 22%",
    color: "ชมพูบานเย็น",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "เอวสูงพยุง",
      "ยืดสี่ทิศทาง",
      "ไม่โปร่งแสง",
      "ไร้ตะเข็บด้านข้าง",
    ],
    activities: ["โยคะ", "พิลาทิส", "บาร์", "สตรีทชิง"],
    sizeGuide: [
      { size: "XS", waist: "56–59 ซม." },
      { size: "S", waist: "59–64 ซม." },
      { size: "M", waist: "64–69 ซม." },
      { size: "L", waist: "69–74 ซม." },
      { size: "XL", waist: "74–79 ซม." },
    ],
    careNote:
      "ตรวจสอบความยืดหยุ่นและความทึบของผ้าหลังซักทุกครั้ง",
  },
  {
    id: "pilates-set",
    name: "ชุดพิลาทิส ครบเซ็ต",
    description: "บรา + กางเกงขาสั้น ชุดเดียวจบ พร้อมเข้าคลาส",
    longDescription:
      "ชุดพิลาทิสครบเซ็ตประกอบด้วยสปอร์ตบราและกางเกงขาสั้นรัดรูป ผ้านุ่มยืดหยุ่น กระชับสัดส่วน เหมาะพิลาทิส โยคะ และบาร์",
    category: "set",
    image: "/products/pilates-set.jpg",
    pricePerRental: 95,
    material: "ไนลอน 75% + สแปนเด็กซ์ 25%",
    color: "ม่วงอ่อน",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "ครบเซ็ต บรา + กางเกง",
      "กระชับสัดส่วน",
      "ผ้านุ่ม ยืดหยุ่น",
      "ประหยัดกว่าเช่าแยกชิ้น",
    ],
    activities: ["พิลาทิส", "โยคะ", "บาร์", "สตรีทชิง"],
    sizeGuide: [
      { size: "XS", chest: "74–79 ซม.", waist: "56–59 ซม." },
      { size: "S", chest: "79–84 ซม.", waist: "59–64 ซม." },
      { size: "M", chest: "84–89 ซม.", waist: "64–69 ซม." },
      { size: "L", chest: "89–95 ซม.", waist: "69–74 ซม." },
      { size: "XL", chest: "95–100 ซม.", waist: "74–79 ซม." },
    ],
    careNote:
      "ชุดเซ็ตบรรจุแยกชิ้นในถุงซิปล็อกคู่ เพื่อความสะอาดและง่ายต่อการตรวจสอบ",
  },
  {
    id: "compression-tee",
    name: "เสื้อรัดกล้ามเนื้อ",
    description: "เสื้อรัดรูป ช่วยพยุงกล้ามเนื้อ เหมาะเวทและ CrossFit",
    longDescription:
      "เสื้อรัดกล้ามเนื้อผ้ายืดสี่ทิศทาง ช่วยพยุงและลดการสั่นของกล้ามเนื้อ เหมาะเวทเทรนนิ่ง CrossFit และฝึกความแข็งแรง",
    category: "top",
    image: "/products/compression-tee.jpg",
    pricePerRental: 55,
    material: "โพลีเอสเตอร์ 82% + สแปนเด็กซ์ 18%",
    color: "ดำ",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "รัดรูปพยุงกล้ามเนื้อ",
      "ผ้ายืดสี่ทิศทาง",
      "ทนทานต่อการเสียดสี",
      "กลิ่นอับน้อย",
    ],
    activities: ["เวทเทรนนิ่ง", "CrossFit", "HIIT", "ฟังก์ชันนัล"],
    sizeGuide: [
      { size: "XS", chest: "76–81 ซม." },
      { size: "S", chest: "81–86 ซม." },
      { size: "M", chest: "86–91 ซม." },
      { size: "L", chest: "91–97 ซม." },
      { size: "XL", chest: "97–102 ซม." },
    ],
    careNote:
      "ตรวจสอบความยืดหยุ่นของผ้าหลังซักทุกครั้ง เพื่อการพยุงที่เหมาะสม",
  },
  {
    id: "crossfit-shorts",
    name: "กางเกงขาสั้น CrossFit",
    description: "กางเกงทนทาน ยืดหยุ่นสูง มีกระเป๋าซ่อน",
    longDescription:
      "กางเกงขาสั้น CrossFit ผ้าทนทานต่อการเสียดสี ยืดหยุ่นสูง มีกระเป๋าซ่อนด้านข้าง เหมาะเวท ฟังก์ชันนัล และ WOD",
    category: "bottom",
    image: "/products/crossfit-shorts.jpg",
    pricePerRental: 49,
    material: "โพลีเอสเตอร์ 90% + สแปนเด็กซ์ 10%",
    color: "เทาเข้ม",
    sizes: apparelSizes,
    sizeUnit: "ตัว",
    features: [
      "ผ้าทนทาน",
      "ยืดหยุ่นสูง",
      "กระเป๋าซ่อนด้านข้าง",
      "เหมาะ WOD",
    ],
    activities: ["CrossFit", "เวทเทรนนิ่ง", "HIIT", "ฟังก์ชันนัล"],
    sizeGuide: [
      { size: "XS", waist: "58–61 ซม." },
      { size: "S", waist: "61–66 ซม." },
      { size: "M", waist: "66–71 ซม." },
      { size: "L", waist: "71–76 ซม." },
      { size: "XL", waist: "76–81 ซม." },
    ],
    careNote:
      "ตรวจสอบกระเป๋าและตะเข็บทุกครั้งก่อนส่งมอบ ซักตามมาตรฐานสุขอนามัย",
  },
  {
    id: "crossfit-shoes",
    name: "รองเท้า CrossFit",
    description: "รองเท้าพื้นแบนราบ เกาะพื้นดี ทนทานต่อการยืดหยุ่น",
    longDescription:
      "รองเท้า CrossFit หน้ากว้าง พื้นแบนราบช่วยเกาะพื้น โฟมรองรับส้นเท้า ทนต่อการยืดหยุ่นและเสียดสี เหมาะ WOD เวท และฟังก์ชันนัล",
    category: "shoe",
    image: "/products/crossfit-shoes.jpg",
    pricePerRental: 72,
    material: "หนังสังเคราะห์ + โฟม + พื้นยาง",
    color: "ดำ-เขียว",
    sizes: shoeSizes,
    sizeUnit: "คู่",
    features: [
      "พื้นแบนราบ เกาะพื้นดี",
      "หน้ากว้าง สวมใส่สบาย",
      "ทนทานต่อการยืดหยุ่น",
      "ทำความสะอาดทุกครั้ง",
    ],
    activities: ["CrossFit", "เวทเทรนนิ่ง", "HIIT", "ฟังก์ชันนัล"],
    sizeGuide: [
      { size: "38", footLength: "24.0 ซม." },
      { size: "39", footLength: "24.5 ซม." },
      { size: "40", footLength: "25.0 ซม." },
      { size: "41", footLength: "25.5 ซม." },
      { size: "42", footLength: "26.0 ซม." },
      { size: "43", footLength: "26.5 ซม." },
    ],
    careNote:
      "ตรวจสอบพื้นรองเท้าและตะเข็บทุกครั้งหลังคืน ทำความสะอาดและฆ่าเชื้อก่อนส่งมอบ",
  },
];
