import type { RentalLocation } from "../lib/types";

export const rentalLocations: RentalLocation[] = [
  {
    id: "lumpini",
    name: "สวนลุมพินี",
    address: "ถ. พระราม 4 แขวงลุมพินี เขตปทุมวัน กรุงเทพฯ",
    lat: 13.7307,
    lng: 100.5418,
    type: "booth",
    openHours: "06:00 – 20:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 2, S: 3, M: 4, L: 3, XL: 1 } },
      { productId: "running-shorts", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "leggings", inventory: { XS: 0, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "yoga-set", inventory: { XS: 1, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "running-shoes", inventory: { "38": 1, "39": 2, "40": 3, "41": 2, "42": 1, "43": 0 } },
      { productId: "training-shoes", inventory: { "38": 0, "39": 1, "40": 2, "41": 2, "42": 1, "43": 1 } },
      { productId: "sports-tank-top", inventory: { XS: 2, S: 3, M: 3, L: 2, XL: 1 } },
      { productId: "training-pants", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "walk-shoes", inventory: { "38": 1, "39": 1, "40": 2, "41": 2, "42": 1, "43": 0 } },
      { productId: "yoga-bra", inventory: { XS: 1, S: 2, M: 2, L: 1, XL: 1 } },
      { productId: "pilates-shorts", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "pilates-set", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "compression-tee", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "crossfit-shorts", inventory: { XS: 1, S: 2, M: 2, L: 2, XL: 1 } },
      { productId: "crossfit-shoes", inventory: { "38": 0, "39": 1, "40": 2, "41": 2, "42": 1, "43": 0 } },
    ],
  },
  {
    id: "siam",
    name: "สยามสแควร์",
    address: "ถ. พระราม 1 แขวงปทุมวัน เขตปทุมวัน กรุงเทพฯ",
    lat: 13.7466,
    lng: 100.5347,
    type: "qr",
    openHours: "24 ชม.",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 1, S: 2, M: 2, L: 1, XL: 0 } },
      { productId: "running-shorts", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "leggings", inventory: { XS: 0, S: 1, M: 1, L: 0, XL: 0 } },
      { productId: "running-shoes", inventory: { "38": 0, "39": 1, "40": 2, "41": 1, "42": 0, "43": 0 } },
      { productId: "sports-tank-top", inventory: { XS: 1, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "walk-shoes", inventory: { "38": 0, "39": 1, "40": 1, "41": 1, "42": 0, "43": 0 } },
    ],
  },
  {
    id: "asoke",
    name: "อโศก (BTS)",
    address: "ถ. สุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพฯ",
    lat: 13.7373,
    lng: 100.5608,
    type: "booth",
    openHours: "05:30 – 22:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 3, S: 4, M: 5, L: 3, XL: 2 } },
      { productId: "running-shorts", inventory: { XS: 2, S: 3, M: 4, L: 2, XL: 1 } },
      { productId: "leggings", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "yoga-set", inventory: { XS: 1, S: 2, M: 2, L: 1, XL: 1 } },
      { productId: "running-shoes", inventory: { "38": 2, "39": 2, "40": 4, "41": 3, "42": 2, "43": 1 } },
      { productId: "training-shoes", inventory: { "38": 1, "39": 2, "40": 3, "41": 2, "42": 2, "43": 0 } },
      { productId: "sports-tank-top", inventory: { XS: 2, S: 3, M: 4, L: 3, XL: 2 } },
      { productId: "training-pants", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "walk-shoes", inventory: { "38": 1, "39": 2, "40": 3, "41": 2, "42": 1, "43": 1 } },
      { productId: "yoga-bra", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "pilates-shorts", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "pilates-set", inventory: { XS: 1, S: 1, M: 2, L: 1, XL: 1 } },
      { productId: "compression-tee", inventory: { XS: 2, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "crossfit-shorts", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "crossfit-shoes", inventory: { "38": 1, "39": 2, "40": 2, "41": 2, "42": 1, "43": 0 } },
      { productId: "nike-pegasus", inventory: { "38": 1, "39": 1, "40": 2, "41": 2, "42": 1, "43": 0 } },
      { productId: "nb-1080", inventory: { "38": 0, "39": 1, "40": 1, "41": 1, "42": 1, "43": 0 } },
    ],
  },
  {
    id: "samyan",
    name: "สามย่าน",
    address: "ถ. พญาไท แขวงวังใหม่ เขตปทุมวัน กรุงเทพฯ",
    lat: 13.7324,
    lng: 100.5271,
    type: "partner",
    partnerName: "Fitness First สามย่าน",
    openHours: "06:00 – 21:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 0, S: 1, M: 3, L: 2, XL: 1 } },
      { productId: "leggings", inventory: { XS: 0, S: 1, M: 2, L: 2, XL: 0 } },
      { productId: "yoga-set", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "training-shoes", inventory: { "38": 0, "39": 1, "40": 2, "41": 1, "42": 1, "43": 0 } },
      { productId: "yoga-bra", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "pilates-shorts", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "pilates-set", inventory: { XS: 0, S: 1, M: 1, L: 1, XL: 0 } },
      { productId: "compression-tee", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "crossfit-shoes", inventory: { "38": 0, "39": 1, "40": 1, "41": 1, "42": 0, "43": 0 } },
      { productId: "nike-pegasus", inventory: { "38": 0, "39": 1, "40": 1, "41": 1, "42": 0, "43": 0 } },
      { productId: "adidas-ultraboost", inventory: { "38": 0, "39": 1, "40": 2, "41": 1, "42": 1, "43": 0 } },
    ],
  },
  {
    id: "chatuchak",
    name: "สวนจตุจักร",
    address: "ถ. พหลโยธิน แขวงจตุจักร เขตจตุจักร กรุงเทพฯ",
    lat: 13.7999,
    lng: 100.5501,
    type: "booth",
    openHours: "05:00 – 19:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 2, S: 3, M: 4, L: 3, XL: 2 } },
      { productId: "running-shorts", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "leggings", inventory: { XS: 1, S: 2, M: 3, L: 3, XL: 2 } },
      { productId: "yoga-set", inventory: { XS: 1, S: 1, M: 2, L: 2, XL: 1 } },
      { productId: "running-shoes", inventory: { "38": 1, "39": 2, "40": 3, "41": 3, "42": 2, "43": 1 } },
      { productId: "adidas-ultraboost", inventory: { "38": 1, "39": 1, "40": 2, "41": 2, "42": 1, "43": 0 } },
      { productId: "yoga-bra", inventory: { XS: 1, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "pilates-shorts", inventory: { XS: 1, S: 2, M: 2, L: 1, XL: 1 } },
    ],
  },
  {
    id: "thonglor",
    name: "ทองหล่อ",
    address: "ถ. สุขุมวิท แขวงคลองตันเหนือ เขตวัฒนา กรุงเทพฯ",
    lat: 13.7234,
    lng: 100.5785,
    type: "partner",
    partnerName: "Virgin Active ทองหล่อ",
    openHours: "06:00 – 22:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 1, S: 2, M: 2, L: 1, XL: 0 } },
      { productId: "running-shorts", inventory: { XS: 1, S: 1, M: 1, L: 0, XL: 0 } },
      { productId: "yoga-set", inventory: { XS: 0, S: 1, M: 1, L: 0, XL: 0 } },
      { productId: "running-shoes", inventory: { "38": 0, "39": 1, "40": 1, "41": 1, "42": 0, "43": 0 } },
      { productId: "training-shoes", inventory: { "38": 0, "39": 0, "40": 1, "41": 1, "42": 1, "43": 0 } },
      { productId: "pilates-set", inventory: { XS: 0, S: 1, M: 1, L: 0, XL: 0 } },
      { productId: "crossfit-shorts", inventory: { XS: 0, S: 1, M: 1, L: 1, XL: 0 } },
      { productId: "nb-1080", inventory: { "38": 0, "39": 1, "40": 1, "41": 1, "42": 0, "43": 0 } },
      { productId: "on-cloudrunner", inventory: { "38": 0, "39": 0, "40": 1, "41": 1, "42": 1, "43": 0 } },
    ],
  },
  {
    id: "benjakitti",
    name: "สวนเบญจกิติ",
    address: "ถ. รัชดาภิเษก แขวงคลองเตย เขตคลองเตย กรุงเทพฯ",
    lat: 13.7226,
    lng: 100.5593,
    type: "booth",
    openHours: "05:30 – 20:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 2, S: 3, M: 4, L: 3, XL: 1 } },
      { productId: "running-shorts", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "leggings", inventory: { XS: 1, S: 2, M: 2, L: 2, XL: 1 } },
      { productId: "running-shoes", inventory: { "38": 1, "39": 2, "40": 2, "41": 2, "42": 1, "43": 0 } },
      { productId: "sports-tank-top", inventory: { XS: 1, S: 2, M: 2, L: 2, XL: 1 } },
      { productId: "training-pants", inventory: { XS: 1, S: 1, M: 2, L: 2, XL: 1 } },
    ],
  },
  {
    id: "central-park",
    name: "Central Park",
    address: "ถ. ราชดำริ แขวงลุมพินี เขตปทุมวัน กรุงเทพฯ",
    lat: 13.72829,
    lng: 100.53782,
    type: "booth",
    openHours: "06:00 – 20:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 2, S: 3, M: 4, L: 3, XL: 1 } },
      { productId: "running-shorts", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "leggings", inventory: { XS: 1, S: 2, M: 2, L: 2, XL: 1 } },
      { productId: "running-shoes", inventory: { "38": 1, "39": 2, "40": 2, "41": 2, "42": 1, "43": 0 } },
      { productId: "sports-tank-top", inventory: { XS: 1, S: 2, M: 2, L: 2, XL: 1 } },
      { productId: "training-pants", inventory: { XS: 1, S: 1, M: 2, L: 2, XL: 1 } },
    ],
  },
  {
    id: "sirikit",
    name: "ศูนย์ประชุมแห่งชาติสิริกิติ์",
    address: "ถ. รัชดาภิเษก แขวงคลองเตย เขตคลองเตย กรุงเทพฯ",
    lat: 13.7226,
    lng: 100.5597,
    type: "booth",
    openHours: "06:00 – 21:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "running-shorts", inventory: { XS: 1, S: 2, M: 2, L: 2, XL: 0 } },
      { productId: "yoga-set", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "training-shoes", inventory: { "38": 0, "39": 1, "40": 2, "41": 1, "42": 1, "43": 0 } },
      { productId: "compression-tee", inventory: { XS: 1, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "crossfit-shorts", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "crossfit-shoes", inventory: { "38": 0, "39": 1, "40": 1, "41": 1, "42": 1, "43": 0 } },
    ],
  },
  {
    id: "rotfai",
    name: "สวนรถไฟ (สวนวชิรเบญจทัศ)",
    address: "สวนวชิรเบญจทัศ ถ. กำแพงเพชร แขวงจตุจักร เขตจตุจักร กรุงเทพฯ",
    // Wachirabenchathat Park (Rot Fai Park) approximate landmark coordinates
    // Source: public coordinate references for the park
    lat: 13.811944,
    lng: 100.553889,
    type: "booth",
    openHours: "05:00 – 19:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "running-shorts", inventory: { XS: 1, S: 2, M: 2, L: 2, XL: 0 } },
      { productId: "leggings", inventory: { XS: 0, S: 1, M: 2, L: 2, XL: 1 } },
      { productId: "yoga-set", inventory: { XS: 1, S: 1, M: 1, L: 1, XL: 0 } },
      { productId: "pilates-shorts", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "running-shoes", inventory: { "38": 0, "39": 1, "40": 2, "41": 2, "42": 1, "43": 0 } },
    ],
  },
  {
    id: "silom",
    name: "สีลม (BTS ศาลาแดง)",
    address: "ถ. สีลม แขวงสีลม เขตบางรัก กรุงเทพฯ",
    lat: 13.7263,
    lng: 100.5238,
    type: "booth",
    openHours: "06:00 – 21:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 2, S: 3, M: 4, L: 2, XL: 1 } },
      { productId: "running-shorts", inventory: { XS: 1, S: 2, M: 2, L: 2, XL: 1 } },
      { productId: "training-shoes", inventory: { "38": 1, "39": 1, "40": 2, "41": 2, "42": 1, "43": 0 } },
      { productId: "crossfit-shorts", inventory: { XS: 1, S: 1, M: 2, L: 1, XL: 0 } },
    ],
  },
  {
    id: "rama9",
    name: "สวนเฉลิมพระเกียริตฯ ร.9",
    address: "ถ. ศรีนครินทร์ แขวงหนองบอน เขตประเวศ กรุงเทพฯ",
    lat: 13.7649,
    lng: 100.643,
    type: "booth",
    openHours: "05:00 – 20:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 2, S: 3, M: 3, L: 3, XL: 2 } },
      { productId: "running-shorts", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "leggings", inventory: { XS: 1, S: 2, M: 2, L: 2, XL: 1 } },
      { productId: "running-shoes", inventory: { "38": 1, "39": 2, "40": 3, "41": 2, "42": 1, "43": 1 } },
      { productId: "training-shoes", inventory: { "38": 0, "39": 1, "40": 1, "41": 2, "42": 1, "43": 0 } },
      { productId: "sports-tank-top", inventory: { XS: 2, S: 2, M: 3, L: 2, XL: 2 } },
      { productId: "walk-shoes", inventory: { "38": 1, "39": 1, "40": 2, "41": 2, "42": 1, "43": 0 } },
      { productId: "pilates-set", inventory: { XS: 1, S: 1, M: 1, L: 1, XL: 0 } },
      { productId: "compression-tee", inventory: { XS: 1, S: 2, M: 2, L: 2, XL: 1 } },
      { productId: "crossfit-shoes", inventory: { "38": 0, "39": 1, "40": 2, "41": 1, "42": 1, "43": 0 } },
    ],
  },
  {
    id: "phromphong",
    name: "พร้อมพงษ์ (BTS)",
    address: "ถ. สุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพฯ",
    lat: 13.73,
    lng: 100.5695,
    type: "booth",
    openHours: "05:30 – 22:00",
    products: [
      { productId: "dri-fit-tee", inventory: { XS: 1, S: 2, M: 3, L: 2, XL: 1 } },
      { productId: "running-shorts", inventory: { XS: 0, S: 1, M: 2, L: 2, XL: 1 } },
      { productId: "yoga-set", inventory: { XS: 1, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "leggings", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 1 } },
      { productId: "yoga-bra", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 0 } },
      { productId: "pilates-shorts", inventory: { XS: 0, S: 1, M: 2, L: 1, XL: 1 } },
      { productId: "running-shoes", inventory: { "38": 0, "39": 1, "40": 2, "41": 2, "42": 1, "43": 0 } },
    ],
  },
];
