export type JettsBranch = {
  id: string;
  name: string;
  lat: number;
  lng: number;
  note: string;
};

export const jettsBranches: JettsBranch[] = [
  // โซนใจกลางเมืองและย่านธุรกิจ (CBD)
  {
    id: "siam-square-one",
    name: "สยามสแควร์วัน",
    lat: 13.7441,
    lng: 100.5348,
    note: "ชั้น 6 ห้าง Siam Square One (BTS สยาม)",
  },
  {
    id: "stadium-one",
    name: "สเตเดียมวัน (จุฬา)",
    lat: 13.744,
    lng: 100.5234,
    note: "โครงการ Stadium One ซอยจุฬาฯ 6 (บรรทัดทอง)",
  },
  {
    id: "park-silom",
    name: "พาร์ค สีลม (Jetts Black)",
    lat: 13.7285,
    lng: 100.5342,
    note: "อาคาร Park Silom (BTS ศาลาแดง / MRT สีลม)",
  },
  {
    id: "silom-connect",
    name: "สีลม คอนเนค",
    lat: 13.7237,
    lng: 100.5293,
    note: "โครงการ Silom Connect (BTS ช่องนนทรี ทางออก 4)",
  },
  {
    id: "one-bangkok",
    name: "วัน แบงค็อก (Jetts Black)",
    lat: 13.7275,
    lng: 100.5478,
    note: "โครงการ One Bangkok (MRT ลุมพินี)",
  },
  {
    id: "asoke-exchange",
    name: "อโศก",
    lat: 13.7374,
    lng: 100.5604,
    note: "อาคาร Exchange Tower (BTS อโศก / MRT สุขุมวิท)",
  },
  {
    id: "donki-ekamai",
    name: "ดองกี้ มอลล์ (เอกมัย)",
    lat: 13.7335,
    lng: 100.5891,
    note: "ชั้น 2 ห้าง DONKI Mall Thonglor-Ekamai",
  },
  {
    id: "canvas-ploenchit",
    name: "แคนวาส (เพลินจิต)",
    lat: 13.7428,
    lng: 100.5492,
    note: "โครงการ Canvas Ploenchit (BTS เพลินจิต)",
  },
  {
    id: "gaysorn-village",
    name: "เกษรวิลเลจ",
    lat: 13.7449,
    lng: 100.5402,
    note: "ห้าง Gaysorn Village (BTS ชิดลม)",
  },
  {
    id: "the-unicorn",
    name: "เดอะ ยูนิคอร์น",
    lat: 13.7562,
    lng: 100.5341,
    note: "อาคาร The Unicorn (BTS พญาไท)",
  },
  {
    id: "sp-building-ari",
    name: "อาคาร เอส พี (อารีย์)",
    lat: 13.7788,
    lng: 100.5447,
    note: "ชั้น G อาคาร IBM/SP Building (BTS อารีย์)",
  },
  {
    id: "victory-hub",
    name: "วิคตอรี่ ฮับ",
    lat: 13.7645,
    lng: 100.5376,
    note: "ห้าง Victory Hub เกาะดินแดง (BTS อนุสาวรีย์ชัยฯ)",
  },
  {
    id: "the-street-ratchada",
    name: "เดอะสตรีท รัชดา",
    lat: 13.7702,
    lng: 100.5732,
    note: "ชั้น 3 ห้าง The Street Ratchada (เปิด 24 ชม.)",
  },
  {
    id: "unilever-house",
    name: "ยูนิลีเวอร์ เฮ้าส์",
    lat: 13.757,
    lng: 100.5661,
    note: "อาคาร Unilever House (MRT พระราม 9)",
  },
  {
    id: "sj-infinite-one",
    name: "เอสเจ อินฟินิท วัน",
    lat: 13.8082,
    lng: 100.5574,
    note: "อาคาร SJ Infinite One Business Complex (วิภาวดี-จตุจักร)",
  },
  {
    id: "gateway-bangsue",
    name: "เกตเวย์ บางซื่อ",
    lat: 13.8062,
    lng: 100.5218,
    note: "ห้าง Gateway Bangsue (MRT บางโพ)",
  },
  {
    id: "the-parq",
    name: "เดอะพาร์ค (Jetts Black)",
    lat: 13.7214,
    lng: 100.557,
    note: "ชั้น 3 อาคาร The PARQ (MRT ศูนย์ฯ สิริกิติ์)",
  },
  {
    id: "suanplern-market",
    name: "สวนเพลิน มาร์เก็ต",
    lat: 13.7168,
    lng: 100.5694,
    note: "โครงการ Suanplern Market (ถนนพระราม 4 ตรงข้ามช่อง 3)",
  },
  {
    id: "im-chinatown",
    name: "แอมไชน่าทาวน์",
    lat: 13.7423,
    lng: 100.5126,
    note: "ห้าง I'm Chinatown (MRT วัดมังกร)",
  },
  {
    id: "ms-siam-tower",
    name: "เอ็มเอส สยาม ทาวเวอร์",
    lat: 13.6822,
    lng: 100.546,
    note: "อาคาร MS Siam Tower (หัวมุมถนนพระราม 3 - นราธิวาสฯ)",
  },
  {
    id: "marketplace-dusit",
    name: "มาร์เก็ต เพลส ดุสิต",
    lat: 13.782,
    lng: 100.5135,
    note: "โครงการ Market Place Dusit (ถนนราชวิถี)",
  },

  // โซนกรุงเทพฯ รอบนอก (ตะวันออก / เหนือ / ใต้)
  {
    id: "the-phyll-onnut",
    name: "เดอะฟิล (อ่อนนุช)",
    lat: 13.7058,
    lng: 100.6006,
    note: "โครงการ The Phyll Sukhumvit 54 (BTS อ่อนนุช)",
  },
  {
    id: "bangchak",
    name: "บางจาก",
    lat: 13.697,
    lng: 100.6053,
    note: "โครงการ M Tower (BTS บางจาก)",
  },
  {
    id: "the-glass-bangna",
    name: "เดอะกลาส บางนา",
    lat: 13.6664,
    lng: 100.6125,
    note: "โครงการ The Glass House (สี่แยกบางนา)",
  },
  {
    id: "robinson-latkrabang",
    name: "โรบินสัน ลาดกระบัง",
    lat: 13.7225,
    lng: 100.7275,
    note: "ห้าง Robinson Lifestyle Lat Krabang",
  },
  {
    id: "navamin-city-avenue",
    name: "นวมินทร์ ซิตี้ อเวนิว",
    lat: 13.8268,
    lng: 100.6055,
    note: "โครงการ Navamin City Avenue (เกษตร-นวมินทร์)",
  },
  {
    id: "the-walk-kaset",
    name: "เดอะวอล์ค เกษตรนวมินทร์",
    lat: 13.8115,
    lng: 100.6186,
    note: "ห้าง The Walk Kaset-Nawamin",
  },
  {
    id: "the-scene-town-in-town",
    name: "เดอะซีน (ทาวน์อินทาวน์)",
    lat: 13.7719,
    lng: 100.6021,
    note: "โครงการ The Scene Town in Town",
  },
  {
    id: "amorini-ramintra",
    name: "อมอรินี่ (รามอินทรา)",
    lat: 13.8052,
    lng: 100.6792,
    note: "โครงการ Amorini Boutique Lifestyle Mall (แยกสวนสยาม)",
  },
  {
    id: "life-ramintra",
    name: "ไลฟ์ รามอินทรา",
    lat: 13.8601,
    lng: 100.6432,
    note: "โครงการ ไลฟ์ รามอินทรา (ติดถนนใหญ่)",
  },
  {
    id: "saimai-avenue",
    name: "สายไหม อเวนิว",
    lat: 13.9135,
    lng: 100.6485,
    note: "โครงการ Saimai Avenue (ถนนสายไหม)",
  },
  {
    id: "sena-fest",
    name: "เสนา เฟสท์",
    lat: 13.7211,
    lng: 100.5053,
    note: "ชั้น 2 โครงการ Sena Fest (เจริญนคร/ฝั่งธนฯ)",
  },
  {
    id: "index-rama2",
    name: "อินเดกซ์ ลิฟวิ่ง มอลล์ พระราม 2",
    lat: 13.6668,
    lng: 100.4411,
    note: "ภายในอาคาร Index Living Mall พระราม 2",
  },
  {
    id: "the-fourth-phutthamonthon",
    name: "เดอะโฟร์ท (พุทธมณฑล สาย 4)",
    lat: 13.7371,
    lng: 100.3323,
    note: "โครงการ The Fourth (พุทธมณฑล สาย 4 โซนทวีวัฒนา)",
  },

  // โซนปริมณฑล (นนทบุรี / ปทุมธานี / สมุทรปราการ)
  {
    id: "cosmo-bazaar-muangthong",
    name: "คอสโม บาร์ซาร์ (เมืองทอง)",
    lat: 13.9126,
    lng: 100.5487,
    note: "ชั้น 4 อาคาร Cosmo Bazaar เมืองทองธานี",
  },
  {
    id: "index-bangyai",
    name: "อินเดกซ์ ลิฟวิ่ง มอลล์ บางใหญ่",
    lat: 13.8763,
    lng: 100.4109,
    note: "Index Living Mall บางใหญ่ (MRT ตลาดบางใหญ่)",
  },
  {
    id: "little-walk-rattanathibet",
    name: "ลิตเติ้ลวอล์ค รัตนาธิเบศร์",
    lat: 13.8615,
    lng: 100.4745,
    note: "โครงการ Little Walk Rattanathibet",
  },
  {
    id: "central-westville",
    name: "เซ็นทรัล เวสต์วิลล์",
    lat: 13.8054,
    lng: 100.4497,
    note: "ห้าง Central Westville (ถนนราชพฤกษ์)",
  },
  {
    id: "robinson-srisamarn",
    name: "โรบินสัน ไลฟ์สไตล์ ศรีสมาน",
    lat: 13.9351,
    lng: 100.563,
    note: "ห้าง Robinson Lifestyle Srisamarn",
  },
  {
    id: "robinson-ratchaphruek",
    name: "โรบินสัน ไลฟ์สไตล์ ราชพฤกษ์",
    lat: 13.9182,
    lng: 100.4547,
    note: "ห้าง Robinson Lifestyle Ratchaphruek",
  },
  {
    id: "future-city-rangsit",
    name: "ฟิวเจอร์ ซิตี้ รังสิต",
    lat: 13.9892,
    lng: 100.6178,
    note: "โครงการ Future City (โซนฟิวเจอร์พาร์ค รังสิต)",
  },
  {
    id: "rest-park-suvarnabhumi",
    name: "เรสต์ พาร์ค สุวรรณภูมิ",
    lat: 13.6231,
    lng: 100.7511,
    note: "โครงการ Rest Park สุวรรณภูมิ (โซนสมุทรปราการ)",
  },
];
